/*
 * This file is generated by jOOQ.
 */
package races.f1db.model.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Circuits implements Serializable {

    private static final long serialVersionUID = -1888585597;

    private Integer circuitid;
    private String  circuitref;
    private String  name;
    private String  location;
    private String  country;
    private Double  lat;
    private Double  lng;
    private Integer alt;
    private String  url;

    public Circuits() {}

    public Circuits(Circuits value) {
        this.circuitid = value.circuitid;
        this.circuitref = value.circuitref;
        this.name = value.name;
        this.location = value.location;
        this.country = value.country;
        this.lat = value.lat;
        this.lng = value.lng;
        this.alt = value.alt;
        this.url = value.url;
    }

    public Circuits(
        Integer circuitid,
        String  circuitref,
        String  name,
        String  location,
        String  country,
        Double  lat,
        Double  lng,
        Integer alt,
        String  url
    ) {
        this.circuitid = circuitid;
        this.circuitref = circuitref;
        this.name = name;
        this.location = location;
        this.country = country;
        this.lat = lat;
        this.lng = lng;
        this.alt = alt;
        this.url = url;
    }

    public Integer getCircuitid() {
        return this.circuitid;
    }

    public void setCircuitid(Integer circuitid) {
        this.circuitid = circuitid;
    }

    public String getCircuitref() {
        return this.circuitref;
    }

    public void setCircuitref(String circuitref) {
        this.circuitref = circuitref;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getLocation() {
        return this.location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    public String getCountry() {
        return this.country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public Double getLat() {
        return this.lat;
    }

    public void setLat(Double lat) {
        this.lat = lat;
    }

    public Double getLng() {
        return this.lng;
    }

    public void setLng(Double lng) {
        this.lng = lng;
    }

    public Integer getAlt() {
        return this.alt;
    }

    public void setAlt(Integer alt) {
        this.alt = alt;
    }

    public String getUrl() {
        return this.url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Circuits (");

        sb.append(circuitid);
        sb.append(", ").append(circuitref);
        sb.append(", ").append(name);
        sb.append(", ").append(location);
        sb.append(", ").append(country);
        sb.append(", ").append(lat);
        sb.append(", ").append(lng);
        sb.append(", ").append(alt);
        sb.append(", ").append(url);

        sb.append(")");
        return sb.toString();
    }
}
