/*
 * This file is generated by jOOQ.
 */
package races.f1db.model.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Constructorstandings implements Serializable {

    private static final long serialVersionUID = -1286914063;

    private Integer constructorstandingsid;
    private Integer raceid;
    private Integer constructorid;
    private Double  points;
    private Integer position;
    private String  positiontext;
    private Integer wins;

    public Constructorstandings() {}

    public Constructorstandings(Constructorstandings value) {
        this.constructorstandingsid = value.constructorstandingsid;
        this.raceid = value.raceid;
        this.constructorid = value.constructorid;
        this.points = value.points;
        this.position = value.position;
        this.positiontext = value.positiontext;
        this.wins = value.wins;
    }

    public Constructorstandings(
        Integer constructorstandingsid,
        Integer raceid,
        Integer constructorid,
        Double  points,
        Integer position,
        String  positiontext,
        Integer wins
    ) {
        this.constructorstandingsid = constructorstandingsid;
        this.raceid = raceid;
        this.constructorid = constructorid;
        this.points = points;
        this.position = position;
        this.positiontext = positiontext;
        this.wins = wins;
    }

    public Integer getConstructorstandingsid() {
        return this.constructorstandingsid;
    }

    public void setConstructorstandingsid(Integer constructorstandingsid) {
        this.constructorstandingsid = constructorstandingsid;
    }

    public Integer getRaceid() {
        return this.raceid;
    }

    public void setRaceid(Integer raceid) {
        this.raceid = raceid;
    }

    public Integer getConstructorid() {
        return this.constructorid;
    }

    public void setConstructorid(Integer constructorid) {
        this.constructorid = constructorid;
    }

    public Double getPoints() {
        return this.points;
    }

    public void setPoints(Double points) {
        this.points = points;
    }

    public Integer getPosition() {
        return this.position;
    }

    public void setPosition(Integer position) {
        this.position = position;
    }

    public String getPositiontext() {
        return this.positiontext;
    }

    public void setPositiontext(String positiontext) {
        this.positiontext = positiontext;
    }

    public Integer getWins() {
        return this.wins;
    }

    public void setWins(Integer wins) {
        this.wins = wins;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Constructorstandings (");

        sb.append(constructorstandingsid);
        sb.append(", ").append(raceid);
        sb.append(", ").append(constructorid);
        sb.append(", ").append(points);
        sb.append(", ").append(position);
        sb.append(", ").append(positiontext);
        sb.append(", ").append(wins);

        sb.append(")");
        return sb.toString();
    }
}
