/*
 * This file is generated by jOOQ.
 */
package races.f1db.model.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Constructors implements Serializable {

    private static final long serialVersionUID = 1580007331;

    private Integer constructorid;
    private String  constructorref;
    private String  name;
    private String  nationality;
    private String  url;

    public Constructors() {}

    public Constructors(Constructors value) {
        this.constructorid = value.constructorid;
        this.constructorref = value.constructorref;
        this.name = value.name;
        this.nationality = value.nationality;
        this.url = value.url;
    }

    public Constructors(
        Integer constructorid,
        String  constructorref,
        String  name,
        String  nationality,
        String  url
    ) {
        this.constructorid = constructorid;
        this.constructorref = constructorref;
        this.name = name;
        this.nationality = nationality;
        this.url = url;
    }

    public Integer getConstructorid() {
        return this.constructorid;
    }

    public void setConstructorid(Integer constructorid) {
        this.constructorid = constructorid;
    }

    public String getConstructorref() {
        return this.constructorref;
    }

    public void setConstructorref(String constructorref) {
        this.constructorref = constructorref;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getNationality() {
        return this.nationality;
    }

    public void setNationality(String nationality) {
        this.nationality = nationality;
    }

    public String getUrl() {
        return this.url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Constructors (");

        sb.append(constructorid);
        sb.append(", ").append(constructorref);
        sb.append(", ").append(name);
        sb.append(", ").append(nationality);
        sb.append(", ").append(url);

        sb.append(")");
        return sb.toString();
    }
}
