/*
 * This file is generated by jOOQ.
 */
package races.f1db.model.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Driverstandings implements Serializable {

    private static final long serialVersionUID = 948525401;

    private Integer driverstandingsid;
    private Integer raceid;
    private Integer driverid;
    private Double  points;
    private Integer position;
    private String  positiontext;
    private Integer wins;

    public Driverstandings() {}

    public Driverstandings(Driverstandings value) {
        this.driverstandingsid = value.driverstandingsid;
        this.raceid = value.raceid;
        this.driverid = value.driverid;
        this.points = value.points;
        this.position = value.position;
        this.positiontext = value.positiontext;
        this.wins = value.wins;
    }

    public Driverstandings(
        Integer driverstandingsid,
        Integer raceid,
        Integer driverid,
        Double  points,
        Integer position,
        String  positiontext,
        Integer wins
    ) {
        this.driverstandingsid = driverstandingsid;
        this.raceid = raceid;
        this.driverid = driverid;
        this.points = points;
        this.position = position;
        this.positiontext = positiontext;
        this.wins = wins;
    }

    public Integer getDriverstandingsid() {
        return this.driverstandingsid;
    }

    public void setDriverstandingsid(Integer driverstandingsid) {
        this.driverstandingsid = driverstandingsid;
    }

    public Integer getRaceid() {
        return this.raceid;
    }

    public void setRaceid(Integer raceid) {
        this.raceid = raceid;
    }

    public Integer getDriverid() {
        return this.driverid;
    }

    public void setDriverid(Integer driverid) {
        this.driverid = driverid;
    }

    public Double getPoints() {
        return this.points;
    }

    public void setPoints(Double points) {
        this.points = points;
    }

    public Integer getPosition() {
        return this.position;
    }

    public void setPosition(Integer position) {
        this.position = position;
    }

    public String getPositiontext() {
        return this.positiontext;
    }

    public void setPositiontext(String positiontext) {
        this.positiontext = positiontext;
    }

    public Integer getWins() {
        return this.wins;
    }

    public void setWins(Integer wins) {
        this.wins = wins;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Driverstandings (");

        sb.append(driverstandingsid);
        sb.append(", ").append(raceid);
        sb.append(", ").append(driverid);
        sb.append(", ").append(points);
        sb.append(", ").append(position);
        sb.append(", ").append(positiontext);
        sb.append(", ").append(wins);

        sb.append(")");
        return sb.toString();
    }
}
