/*
 * This file is generated by jOOQ.
 */
package races.f1db.model.tables.pojos;


import java.io.Serializable;
import java.sql.Date;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Drivers implements Serializable {

    private static final long serialVersionUID = -1547724501;

    private Integer driverid;
    private String  driverref;
    private Integer number;
    private String  code;
    private String  forename;
    private String  surname;
    private Date    dob;
    private String  nationality;
    private String  url;

    public Drivers() {}

    public Drivers(Drivers value) {
        this.driverid = value.driverid;
        this.driverref = value.driverref;
        this.number = value.number;
        this.code = value.code;
        this.forename = value.forename;
        this.surname = value.surname;
        this.dob = value.dob;
        this.nationality = value.nationality;
        this.url = value.url;
    }

    public Drivers(
        Integer driverid,
        String  driverref,
        Integer number,
        String  code,
        String  forename,
        String  surname,
        Date    dob,
        String  nationality,
        String  url
    ) {
        this.driverid = driverid;
        this.driverref = driverref;
        this.number = number;
        this.code = code;
        this.forename = forename;
        this.surname = surname;
        this.dob = dob;
        this.nationality = nationality;
        this.url = url;
    }

    public Integer getDriverid() {
        return this.driverid;
    }

    public void setDriverid(Integer driverid) {
        this.driverid = driverid;
    }

    public String getDriverref() {
        return this.driverref;
    }

    public void setDriverref(String driverref) {
        this.driverref = driverref;
    }

    public Integer getNumber() {
        return this.number;
    }

    public void setNumber(Integer number) {
        this.number = number;
    }

    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getForename() {
        return this.forename;
    }

    public void setForename(String forename) {
        this.forename = forename;
    }

    public String getSurname() {
        return this.surname;
    }

    public void setSurname(String surname) {
        this.surname = surname;
    }

    public Date getDob() {
        return this.dob;
    }

    public void setDob(Date dob) {
        this.dob = dob;
    }

    public String getNationality() {
        return this.nationality;
    }

    public void setNationality(String nationality) {
        this.nationality = nationality;
    }

    public String getUrl() {
        return this.url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Drivers (");

        sb.append(driverid);
        sb.append(", ").append(driverref);
        sb.append(", ").append(number);
        sb.append(", ").append(code);
        sb.append(", ").append(forename);
        sb.append(", ").append(surname);
        sb.append(", ").append(dob);
        sb.append(", ").append(nationality);
        sb.append(", ").append(url);

        sb.append(")");
        return sb.toString();
    }
}
