/*
 * This file is generated by jOOQ.
 */
package races.f1db.model.tables.pojos;


import java.io.Serializable;
import java.sql.Time;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Pitstops implements Serializable {

    private static final long serialVersionUID = -40526139;

    private Integer raceid;
    private Integer driverid;
    private Integer stop;
    private Integer lap;
    private Time    time;
    private String  duration;
    private Integer milliseconds;

    public Pitstops() {}

    public Pitstops(Pitstops value) {
        this.raceid = value.raceid;
        this.driverid = value.driverid;
        this.stop = value.stop;
        this.lap = value.lap;
        this.time = value.time;
        this.duration = value.duration;
        this.milliseconds = value.milliseconds;
    }

    public Pitstops(
        Integer raceid,
        Integer driverid,
        Integer stop,
        Integer lap,
        Time    time,
        String  duration,
        Integer milliseconds
    ) {
        this.raceid = raceid;
        this.driverid = driverid;
        this.stop = stop;
        this.lap = lap;
        this.time = time;
        this.duration = duration;
        this.milliseconds = milliseconds;
    }

    public Integer getRaceid() {
        return this.raceid;
    }

    public void setRaceid(Integer raceid) {
        this.raceid = raceid;
    }

    public Integer getDriverid() {
        return this.driverid;
    }

    public void setDriverid(Integer driverid) {
        this.driverid = driverid;
    }

    public Integer getStop() {
        return this.stop;
    }

    public void setStop(Integer stop) {
        this.stop = stop;
    }

    public Integer getLap() {
        return this.lap;
    }

    public void setLap(Integer lap) {
        this.lap = lap;
    }

    public Time getTime() {
        return this.time;
    }

    public void setTime(Time time) {
        this.time = time;
    }

    public String getDuration() {
        return this.duration;
    }

    public void setDuration(String duration) {
        this.duration = duration;
    }

    public Integer getMilliseconds() {
        return this.milliseconds;
    }

    public void setMilliseconds(Integer milliseconds) {
        this.milliseconds = milliseconds;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Pitstops (");

        sb.append(raceid);
        sb.append(", ").append(driverid);
        sb.append(", ").append(stop);
        sb.append(", ").append(lap);
        sb.append(", ").append(time);
        sb.append(", ").append(duration);
        sb.append(", ").append(milliseconds);

        sb.append(")");
        return sb.toString();
    }
}
