/*
 * This file is generated by jOOQ.
 */
package races.f1db.model.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Qualifying implements Serializable {

    private static final long serialVersionUID = -1345938556;

    private Integer qualifyid;
    private Integer raceid;
    private Integer driverid;
    private Integer constructorid;
    private Integer number;
    private Integer position;
    private String  q1;
    private String  q2;
    private String  q3;

    public Qualifying() {}

    public Qualifying(Qualifying value) {
        this.qualifyid = value.qualifyid;
        this.raceid = value.raceid;
        this.driverid = value.driverid;
        this.constructorid = value.constructorid;
        this.number = value.number;
        this.position = value.position;
        this.q1 = value.q1;
        this.q2 = value.q2;
        this.q3 = value.q3;
    }

    public Qualifying(
        Integer qualifyid,
        Integer raceid,
        Integer driverid,
        Integer constructorid,
        Integer number,
        Integer position,
        String  q1,
        String  q2,
        String  q3
    ) {
        this.qualifyid = qualifyid;
        this.raceid = raceid;
        this.driverid = driverid;
        this.constructorid = constructorid;
        this.number = number;
        this.position = position;
        this.q1 = q1;
        this.q2 = q2;
        this.q3 = q3;
    }

    public Integer getQualifyid() {
        return this.qualifyid;
    }

    public void setQualifyid(Integer qualifyid) {
        this.qualifyid = qualifyid;
    }

    public Integer getRaceid() {
        return this.raceid;
    }

    public void setRaceid(Integer raceid) {
        this.raceid = raceid;
    }

    public Integer getDriverid() {
        return this.driverid;
    }

    public void setDriverid(Integer driverid) {
        this.driverid = driverid;
    }

    public Integer getConstructorid() {
        return this.constructorid;
    }

    public void setConstructorid(Integer constructorid) {
        this.constructorid = constructorid;
    }

    public Integer getNumber() {
        return this.number;
    }

    public void setNumber(Integer number) {
        this.number = number;
    }

    public Integer getPosition() {
        return this.position;
    }

    public void setPosition(Integer position) {
        this.position = position;
    }

    public String getQ1() {
        return this.q1;
    }

    public void setQ1(String q1) {
        this.q1 = q1;
    }

    public String getQ2() {
        return this.q2;
    }

    public void setQ2(String q2) {
        this.q2 = q2;
    }

    public String getQ3() {
        return this.q3;
    }

    public void setQ3(String q3) {
        this.q3 = q3;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Qualifying (");

        sb.append(qualifyid);
        sb.append(", ").append(raceid);
        sb.append(", ").append(driverid);
        sb.append(", ").append(constructorid);
        sb.append(", ").append(number);
        sb.append(", ").append(position);
        sb.append(", ").append(q1);
        sb.append(", ").append(q2);
        sb.append(", ").append(q3);

        sb.append(")");
        return sb.toString();
    }
}
