/*
 * This file is generated by jOOQ.
 */
package races.f1db.model.tables.pojos;


import java.io.Serializable;
import java.sql.Date;
import java.sql.Time;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Races implements Serializable {

    private static final long serialVersionUID = 1787809748;

    private Integer raceid;
    private Integer year;
    private Integer round;
    private Integer circuitid;
    private String  name;
    private Date    date;
    private Time    time;
    private String  url;

    public Races() {}

    public Races(Races value) {
        this.raceid = value.raceid;
        this.year = value.year;
        this.round = value.round;
        this.circuitid = value.circuitid;
        this.name = value.name;
        this.date = value.date;
        this.time = value.time;
        this.url = value.url;
    }

    public Races(
        Integer raceid,
        Integer year,
        Integer round,
        Integer circuitid,
        String  name,
        Date    date,
        Time    time,
        String  url
    ) {
        this.raceid = raceid;
        this.year = year;
        this.round = round;
        this.circuitid = circuitid;
        this.name = name;
        this.date = date;
        this.time = time;
        this.url = url;
    }

    public Integer getRaceid() {
        return this.raceid;
    }

    public void setRaceid(Integer raceid) {
        this.raceid = raceid;
    }

    public Integer getYear() {
        return this.year;
    }

    public void setYear(Integer year) {
        this.year = year;
    }

    public Integer getRound() {
        return this.round;
    }

    public void setRound(Integer round) {
        this.round = round;
    }

    public Integer getCircuitid() {
        return this.circuitid;
    }

    public void setCircuitid(Integer circuitid) {
        this.circuitid = circuitid;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Date getDate() {
        return this.date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    public Time getTime() {
        return this.time;
    }

    public void setTime(Time time) {
        this.time = time;
    }

    public String getUrl() {
        return this.url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Races (");

        sb.append(raceid);
        sb.append(", ").append(year);
        sb.append(", ").append(round);
        sb.append(", ").append(circuitid);
        sb.append(", ").append(name);
        sb.append(", ").append(date);
        sb.append(", ").append(time);
        sb.append(", ").append(url);

        sb.append(")");
        return sb.toString();
    }
}
