/*
 * This file is generated by jOOQ.
 */
package races.f1db.model.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Seasons implements Serializable {

    private static final long serialVersionUID = -1980267699;

    private Integer year;
    private String  url;

    public Seasons() {}

    public Seasons(Seasons value) {
        this.year = value.year;
        this.url = value.url;
    }

    public Seasons(
        Integer year,
        String  url
    ) {
        this.year = year;
        this.url = url;
    }

    public Integer getYear() {
        return this.year;
    }

    public void setYear(Integer year) {
        this.year = year;
    }

    public String getUrl() {
        return this.url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Seasons (");

        sb.append(year);
        sb.append(", ").append(url);

        sb.append(")");
        return sb.toString();
    }
}
