/*
 * This file is generated by jOOQ.
 */
package races.f1db.model.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Status implements Serializable {

    private static final long serialVersionUID = 1441270002;

    private Integer statusid;
    private String  status;

    public Status() {}

    public Status(Status value) {
        this.statusid = value.statusid;
        this.status = value.status;
    }

    public Status(
        Integer statusid,
        String  status
    ) {
        this.statusid = statusid;
        this.status = status;
    }

    public Integer getStatusid() {
        return this.statusid;
    }

    public void setStatusid(Integer statusid) {
        this.statusid = statusid;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Status (");

        sb.append(statusid);
        sb.append(", ").append(status);

        sb.append(")");
        return sb.toString();
    }
}
