/*
 * This file is generated by jOOQ.
 */
package races.f1db.model.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;

import races.f1db.model.tables.Circuits;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CircuitsRecord extends UpdatableRecordImpl<CircuitsRecord> implements Record9<Integer, String, String, String, String, Double, Double, Integer, String> {

    private static final long serialVersionUID = -2093250762;

    /**
     * Setter for <code>public.circuits.circuitid</code>.
     */
    public void setCircuitid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.circuits.circuitid</code>.
     */
    public Integer getCircuitid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.circuits.circuitref</code>.
     */
    public void setCircuitref(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.circuits.circuitref</code>.
     */
    public String getCircuitref() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.circuits.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.circuits.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.circuits.location</code>.
     */
    public void setLocation(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.circuits.location</code>.
     */
    public String getLocation() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.circuits.country</code>.
     */
    public void setCountry(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.circuits.country</code>.
     */
    public String getCountry() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.circuits.lat</code>.
     */
    public void setLat(Double value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.circuits.lat</code>.
     */
    public Double getLat() {
        return (Double) get(5);
    }

    /**
     * Setter for <code>public.circuits.lng</code>.
     */
    public void setLng(Double value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.circuits.lng</code>.
     */
    public Double getLng() {
        return (Double) get(6);
    }

    /**
     * Setter for <code>public.circuits.alt</code>.
     */
    public void setAlt(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.circuits.alt</code>.
     */
    public Integer getAlt() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>public.circuits.url</code>.
     */
    public void setUrl(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.circuits.url</code>.
     */
    public String getUrl() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, String, String, String, String, Double, Double, Integer, String> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, String, String, String, String, Double, Double, Integer, String> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Circuits.CIRCUITS.CIRCUITID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Circuits.CIRCUITS.CIRCUITREF;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Circuits.CIRCUITS.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Circuits.CIRCUITS.LOCATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Circuits.CIRCUITS.COUNTRY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field6() {
        return Circuits.CIRCUITS.LAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field7() {
        return Circuits.CIRCUITS.LNG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return Circuits.CIRCUITS.ALT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return Circuits.CIRCUITS.URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getCircuitid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getCircuitref();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getLocation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getCountry();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component6() {
        return getLat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component7() {
        return getLng();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component8() {
        return getAlt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getCircuitid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getCircuitref();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getLocation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getCountry();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value6() {
        return getLat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value7() {
        return getLng();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getAlt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CircuitsRecord value1(Integer value) {
        setCircuitid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CircuitsRecord value2(String value) {
        setCircuitref(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CircuitsRecord value3(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CircuitsRecord value4(String value) {
        setLocation(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CircuitsRecord value5(String value) {
        setCountry(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CircuitsRecord value6(Double value) {
        setLat(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CircuitsRecord value7(Double value) {
        setLng(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CircuitsRecord value8(Integer value) {
        setAlt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CircuitsRecord value9(String value) {
        setUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CircuitsRecord values(Integer value1, String value2, String value3, String value4, String value5, Double value6, Double value7, Integer value8, String value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CircuitsRecord
     */
    public CircuitsRecord() {
        super(Circuits.CIRCUITS);
    }

    /**
     * Create a detached, initialised CircuitsRecord
     */
    public CircuitsRecord(Integer circuitid, String circuitref, String name, String location, String country, Double lat, Double lng, Integer alt, String url) {
        super(Circuits.CIRCUITS);

        set(0, circuitid);
        set(1, circuitref);
        set(2, name);
        set(3, location);
        set(4, country);
        set(5, lat);
        set(6, lng);
        set(7, alt);
        set(8, url);
    }
}
