/*
 * This file is generated by jOOQ.
 */
package races.f1db.model.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;

import races.f1db.model.tables.Constructorstandings;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ConstructorstandingsRecord extends UpdatableRecordImpl<ConstructorstandingsRecord> implements Record7<Integer, Integer, Integer, Double, Integer, String, Integer> {

    private static final long serialVersionUID = -1387304961;

    /**
     * Setter for <code>public.constructorstandings.constructorstandingsid</code>.
     */
    public void setConstructorstandingsid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.constructorstandings.constructorstandingsid</code>.
     */
    public Integer getConstructorstandingsid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.constructorstandings.raceid</code>.
     */
    public void setRaceid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.constructorstandings.raceid</code>.
     */
    public Integer getRaceid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.constructorstandings.constructorid</code>.
     */
    public void setConstructorid(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.constructorstandings.constructorid</code>.
     */
    public Integer getConstructorid() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.constructorstandings.points</code>.
     */
    public void setPoints(Double value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.constructorstandings.points</code>.
     */
    public Double getPoints() {
        return (Double) get(3);
    }

    /**
     * Setter for <code>public.constructorstandings.position</code>.
     */
    public void setPosition(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.constructorstandings.position</code>.
     */
    public Integer getPosition() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.constructorstandings.positiontext</code>.
     */
    public void setPositiontext(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.constructorstandings.positiontext</code>.
     */
    public String getPositiontext() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.constructorstandings.wins</code>.
     */
    public void setWins(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.constructorstandings.wins</code>.
     */
    public Integer getWins() {
        return (Integer) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Integer, Integer, Double, Integer, String, Integer> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Integer, Integer, Double, Integer, String, Integer> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Constructorstandings.CONSTRUCTORSTANDINGS.CONSTRUCTORSTANDINGSID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Constructorstandings.CONSTRUCTORSTANDINGS.RACEID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Constructorstandings.CONSTRUCTORSTANDINGS.CONSTRUCTORID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field4() {
        return Constructorstandings.CONSTRUCTORSTANDINGS.POINTS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return Constructorstandings.CONSTRUCTORSTANDINGS.POSITION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Constructorstandings.CONSTRUCTORSTANDINGS.POSITIONTEXT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return Constructorstandings.CONSTRUCTORSTANDINGS.WINS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getConstructorstandingsid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getRaceid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getConstructorid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component4() {
        return getPoints();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getPosition();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getPositiontext();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component7() {
        return getWins();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getConstructorstandingsid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getRaceid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getConstructorid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value4() {
        return getPoints();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getPosition();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getPositiontext();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getWins();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ConstructorstandingsRecord value1(Integer value) {
        setConstructorstandingsid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ConstructorstandingsRecord value2(Integer value) {
        setRaceid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ConstructorstandingsRecord value3(Integer value) {
        setConstructorid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ConstructorstandingsRecord value4(Double value) {
        setPoints(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ConstructorstandingsRecord value5(Integer value) {
        setPosition(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ConstructorstandingsRecord value6(String value) {
        setPositiontext(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ConstructorstandingsRecord value7(Integer value) {
        setWins(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ConstructorstandingsRecord values(Integer value1, Integer value2, Integer value3, Double value4, Integer value5, String value6, Integer value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ConstructorstandingsRecord
     */
    public ConstructorstandingsRecord() {
        super(Constructorstandings.CONSTRUCTORSTANDINGS);
    }

    /**
     * Create a detached, initialised ConstructorstandingsRecord
     */
    public ConstructorstandingsRecord(Integer constructorstandingsid, Integer raceid, Integer constructorid, Double points, Integer position, String positiontext, Integer wins) {
        super(Constructorstandings.CONSTRUCTORSTANDINGS);

        set(0, constructorstandingsid);
        set(1, raceid);
        set(2, constructorid);
        set(3, points);
        set(4, position);
        set(5, positiontext);
        set(6, wins);
    }
}
