/*
 * This file is generated by jOOQ.
 */
package races.f1db.model.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;

import races.f1db.model.tables.Qualifying;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QualifyingRecord extends UpdatableRecordImpl<QualifyingRecord> implements Record9<Integer, Integer, Integer, Integer, Integer, Integer, String, String, String> {

    private static final long serialVersionUID = 702443341;

    /**
     * Setter for <code>public.qualifying.qualifyid</code>.
     */
    public void setQualifyid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.qualifying.qualifyid</code>.
     */
    public Integer getQualifyid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.qualifying.raceid</code>.
     */
    public void setRaceid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.qualifying.raceid</code>.
     */
    public Integer getRaceid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.qualifying.driverid</code>.
     */
    public void setDriverid(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.qualifying.driverid</code>.
     */
    public Integer getDriverid() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.qualifying.constructorid</code>.
     */
    public void setConstructorid(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.qualifying.constructorid</code>.
     */
    public Integer getConstructorid() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.qualifying.number</code>.
     */
    public void setNumber(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.qualifying.number</code>.
     */
    public Integer getNumber() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.qualifying.position</code>.
     */
    public void setPosition(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.qualifying.position</code>.
     */
    public Integer getPosition() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.qualifying.q1</code>.
     */
    public void setQ1(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.qualifying.q1</code>.
     */
    public String getQ1() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.qualifying.q2</code>.
     */
    public void setQ2(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.qualifying.q2</code>.
     */
    public String getQ2() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.qualifying.q3</code>.
     */
    public void setQ3(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.qualifying.q3</code>.
     */
    public String getQ3() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, Integer, Integer, Integer, Integer, Integer, String, String, String> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, Integer, Integer, Integer, Integer, Integer, String, String, String> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Qualifying.QUALIFYING.QUALIFYID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Qualifying.QUALIFYING.RACEID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Qualifying.QUALIFYING.DRIVERID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Qualifying.QUALIFYING.CONSTRUCTORID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return Qualifying.QUALIFYING.NUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return Qualifying.QUALIFYING.POSITION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Qualifying.QUALIFYING.Q1;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Qualifying.QUALIFYING.Q2;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return Qualifying.QUALIFYING.Q3;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getQualifyid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getRaceid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getDriverid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getConstructorid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getPosition();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getQ1();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getQ2();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getQ3();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getQualifyid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getRaceid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getDriverid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getConstructorid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getPosition();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getQ1();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getQ2();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getQ3();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QualifyingRecord value1(Integer value) {
        setQualifyid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QualifyingRecord value2(Integer value) {
        setRaceid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QualifyingRecord value3(Integer value) {
        setDriverid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QualifyingRecord value4(Integer value) {
        setConstructorid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QualifyingRecord value5(Integer value) {
        setNumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QualifyingRecord value6(Integer value) {
        setPosition(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QualifyingRecord value7(String value) {
        setQ1(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QualifyingRecord value8(String value) {
        setQ2(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QualifyingRecord value9(String value) {
        setQ3(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QualifyingRecord values(Integer value1, Integer value2, Integer value3, Integer value4, Integer value5, Integer value6, String value7, String value8, String value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached QualifyingRecord
     */
    public QualifyingRecord() {
        super(Qualifying.QUALIFYING);
    }

    /**
     * Create a detached, initialised QualifyingRecord
     */
    public QualifyingRecord(Integer qualifyid, Integer raceid, Integer driverid, Integer constructorid, Integer number, Integer position, String q1, String q2, String q3) {
        super(Qualifying.QUALIFYING);

        set(0, qualifyid);
        set(1, raceid);
        set(2, driverid);
        set(3, constructorid);
        set(4, number);
        set(5, position);
        set(6, q1);
        set(7, q2);
        set(8, q3);
    }
}
