/*
 * This file is generated by jOOQ.
 */
package races.f1db.model.tables.records;


import java.sql.Date;
import java.sql.Time;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;

import races.f1db.model.tables.Races;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RacesRecord extends UpdatableRecordImpl<RacesRecord> implements Record8<Integer, Integer, Integer, Integer, String, Date, Time, String> {

    private static final long serialVersionUID = -945894422;

    /**
     * Setter for <code>public.races.raceid</code>.
     */
    public void setRaceid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.races.raceid</code>.
     */
    public Integer getRaceid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.races.year</code>.
     */
    public void setYear(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.races.year</code>.
     */
    public Integer getYear() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.races.round</code>.
     */
    public void setRound(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.races.round</code>.
     */
    public Integer getRound() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.races.circuitid</code>.
     */
    public void setCircuitid(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.races.circuitid</code>.
     */
    public Integer getCircuitid() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.races.name</code>.
     */
    public void setName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.races.name</code>.
     */
    public String getName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.races.date</code>.
     */
    public void setDate(Date value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.races.date</code>.
     */
    public Date getDate() {
        return (Date) get(5);
    }

    /**
     * Setter for <code>public.races.time</code>.
     */
    public void setTime(Time value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.races.time</code>.
     */
    public Time getTime() {
        return (Time) get(6);
    }

    /**
     * Setter for <code>public.races.url</code>.
     */
    public void setUrl(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.races.url</code>.
     */
    public String getUrl() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, Integer, Integer, Integer, String, Date, Time, String> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, Integer, Integer, Integer, String, Date, Time, String> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Races.RACES.RACEID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Races.RACES.YEAR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Races.RACES.ROUND;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Races.RACES.CIRCUITID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Races.RACES.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field6() {
        return Races.RACES.DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Time> field7() {
        return Races.RACES.TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Races.RACES.URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getRaceid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getYear();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getRound();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getCircuitid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date component6() {
        return getDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Time component7() {
        return getTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getRaceid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getYear();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getRound();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getCircuitid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value6() {
        return getDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Time value7() {
        return getTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RacesRecord value1(Integer value) {
        setRaceid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RacesRecord value2(Integer value) {
        setYear(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RacesRecord value3(Integer value) {
        setRound(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RacesRecord value4(Integer value) {
        setCircuitid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RacesRecord value5(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RacesRecord value6(Date value) {
        setDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RacesRecord value7(Time value) {
        setTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RacesRecord value8(String value) {
        setUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RacesRecord values(Integer value1, Integer value2, Integer value3, Integer value4, String value5, Date value6, Time value7, String value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RacesRecord
     */
    public RacesRecord() {
        super(Races.RACES);
    }

    /**
     * Create a detached, initialised RacesRecord
     */
    public RacesRecord(Integer raceid, Integer year, Integer round, Integer circuitid, String name, Date date, Time time, String url) {
        super(Races.RACES);

        set(0, raceid);
        set(1, year);
        set(2, round);
        set(3, circuitid);
        set(4, name);
        set(5, date);
        set(6, time);
        set(7, url);
    }
}
