/*
 * This file is generated by jOOQ.
 */
package races.f1db.model.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record18;
import org.jooq.Row18;
import org.jooq.impl.UpdatableRecordImpl;

import races.f1db.model.tables.Results;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ResultsRecord extends UpdatableRecordImpl<ResultsRecord> implements Record18<Integer, Integer, Integer, Integer, Integer, Integer, Integer, String, Integer, Double, Integer, String, Integer, Integer, Integer, String, String, Integer> {

    private static final long serialVersionUID = 1777260456;

    /**
     * Setter for <code>public.results.resultid</code>.
     */
    public void setResultid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.results.resultid</code>.
     */
    public Integer getResultid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.results.raceid</code>.
     */
    public void setRaceid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.results.raceid</code>.
     */
    public Integer getRaceid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.results.driverid</code>.
     */
    public void setDriverid(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.results.driverid</code>.
     */
    public Integer getDriverid() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.results.constructorid</code>.
     */
    public void setConstructorid(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.results.constructorid</code>.
     */
    public Integer getConstructorid() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.results.number</code>.
     */
    public void setNumber(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.results.number</code>.
     */
    public Integer getNumber() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.results.grid</code>.
     */
    public void setGrid(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.results.grid</code>.
     */
    public Integer getGrid() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.results.position</code>.
     */
    public void setPosition(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.results.position</code>.
     */
    public Integer getPosition() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>public.results.positiontext</code>.
     */
    public void setPositiontext(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.results.positiontext</code>.
     */
    public String getPositiontext() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.results.positionorder</code>.
     */
    public void setPositionorder(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.results.positionorder</code>.
     */
    public Integer getPositionorder() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>public.results.points</code>.
     */
    public void setPoints(Double value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.results.points</code>.
     */
    public Double getPoints() {
        return (Double) get(9);
    }

    /**
     * Setter for <code>public.results.laps</code>.
     */
    public void setLaps(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.results.laps</code>.
     */
    public Integer getLaps() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>public.results.time</code>.
     */
    public void setTime(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.results.time</code>.
     */
    public String getTime() {
        return (String) get(11);
    }

    /**
     * Setter for <code>public.results.milliseconds</code>.
     */
    public void setMilliseconds(Integer value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.results.milliseconds</code>.
     */
    public Integer getMilliseconds() {
        return (Integer) get(12);
    }

    /**
     * Setter for <code>public.results.fastestlap</code>.
     */
    public void setFastestlap(Integer value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.results.fastestlap</code>.
     */
    public Integer getFastestlap() {
        return (Integer) get(13);
    }

    /**
     * Setter for <code>public.results.rank</code>.
     */
    public void setRank(Integer value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.results.rank</code>.
     */
    public Integer getRank() {
        return (Integer) get(14);
    }

    /**
     * Setter for <code>public.results.fastestlaptime</code>.
     */
    public void setFastestlaptime(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.results.fastestlaptime</code>.
     */
    public String getFastestlaptime() {
        return (String) get(15);
    }

    /**
     * Setter for <code>public.results.fastestlapspeed</code>.
     */
    public void setFastestlapspeed(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.results.fastestlapspeed</code>.
     */
    public String getFastestlapspeed() {
        return (String) get(16);
    }

    /**
     * Setter for <code>public.results.statusid</code>.
     */
    public void setStatusid(Integer value) {
        set(17, value);
    }

    /**
     * Getter for <code>public.results.statusid</code>.
     */
    public Integer getStatusid() {
        return (Integer) get(17);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record18 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row18<Integer, Integer, Integer, Integer, Integer, Integer, Integer, String, Integer, Double, Integer, String, Integer, Integer, Integer, String, String, Integer> fieldsRow() {
        return (Row18) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row18<Integer, Integer, Integer, Integer, Integer, Integer, Integer, String, Integer, Double, Integer, String, Integer, Integer, Integer, String, String, Integer> valuesRow() {
        return (Row18) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Results.RESULTS.RESULTID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Results.RESULTS.RACEID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Results.RESULTS.DRIVERID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Results.RESULTS.CONSTRUCTORID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return Results.RESULTS.NUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return Results.RESULTS.GRID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return Results.RESULTS.POSITION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Results.RESULTS.POSITIONTEXT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return Results.RESULTS.POSITIONORDER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field10() {
        return Results.RESULTS.POINTS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field11() {
        return Results.RESULTS.LAPS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return Results.RESULTS.TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field13() {
        return Results.RESULTS.MILLISECONDS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field14() {
        return Results.RESULTS.FASTESTLAP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field15() {
        return Results.RESULTS.RANK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field16() {
        return Results.RESULTS.FASTESTLAPTIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field17() {
        return Results.RESULTS.FASTESTLAPSPEED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field18() {
        return Results.RESULTS.STATUSID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getResultid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getRaceid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getDriverid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getConstructorid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getGrid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component7() {
        return getPosition();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getPositiontext();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component9() {
        return getPositionorder();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component10() {
        return getPoints();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component11() {
        return getLaps();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component12() {
        return getTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component13() {
        return getMilliseconds();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component14() {
        return getFastestlap();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component15() {
        return getRank();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component16() {
        return getFastestlaptime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component17() {
        return getFastestlapspeed();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component18() {
        return getStatusid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getResultid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getRaceid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getDriverid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getConstructorid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getGrid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getPosition();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getPositiontext();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getPositionorder();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value10() {
        return getPoints();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value11() {
        return getLaps();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value13() {
        return getMilliseconds();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value14() {
        return getFastestlap();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value15() {
        return getRank();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value16() {
        return getFastestlaptime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value17() {
        return getFastestlapspeed();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value18() {
        return getStatusid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ResultsRecord value1(Integer value) {
        setResultid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ResultsRecord value2(Integer value) {
        setRaceid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ResultsRecord value3(Integer value) {
        setDriverid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ResultsRecord value4(Integer value) {
        setConstructorid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ResultsRecord value5(Integer value) {
        setNumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ResultsRecord value6(Integer value) {
        setGrid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ResultsRecord value7(Integer value) {
        setPosition(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ResultsRecord value8(String value) {
        setPositiontext(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ResultsRecord value9(Integer value) {
        setPositionorder(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ResultsRecord value10(Double value) {
        setPoints(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ResultsRecord value11(Integer value) {
        setLaps(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ResultsRecord value12(String value) {
        setTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ResultsRecord value13(Integer value) {
        setMilliseconds(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ResultsRecord value14(Integer value) {
        setFastestlap(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ResultsRecord value15(Integer value) {
        setRank(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ResultsRecord value16(String value) {
        setFastestlaptime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ResultsRecord value17(String value) {
        setFastestlapspeed(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ResultsRecord value18(Integer value) {
        setStatusid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ResultsRecord values(Integer value1, Integer value2, Integer value3, Integer value4, Integer value5, Integer value6, Integer value7, String value8, Integer value9, Double value10, Integer value11, String value12, Integer value13, Integer value14, Integer value15, String value16, String value17, Integer value18) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ResultsRecord
     */
    public ResultsRecord() {
        super(Results.RESULTS);
    }

    /**
     * Create a detached, initialised ResultsRecord
     */
    public ResultsRecord(Integer resultid, Integer raceid, Integer driverid, Integer constructorid, Integer number, Integer grid, Integer position, String positiontext, Integer positionorder, Double points, Integer laps, String time, Integer milliseconds, Integer fastestlap, Integer rank, String fastestlaptime, String fastestlapspeed, Integer statusid) {
        super(Results.RESULTS);

        set(0, resultid);
        set(1, raceid);
        set(2, driverid);
        set(3, constructorid);
        set(4, number);
        set(5, grid);
        set(6, position);
        set(7, positiontext);
        set(8, positionorder);
        set(9, points);
        set(10, laps);
        set(11, time);
        set(12, milliseconds);
        set(13, fastestlap);
        set(14, rank);
        set(15, fastestlaptime);
        set(16, fastestlapspeed);
        set(17, statusid);
    }
}
