/*
 * This file is generated by jOOQ.
 */
package races.f1db.model;


import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;

import races.f1db.model.tables.Circuits;
import races.f1db.model.tables.Constructorresults;
import races.f1db.model.tables.Constructors;
import races.f1db.model.tables.Constructorstandings;
import races.f1db.model.tables.Drivers;
import races.f1db.model.tables.Driverstandings;
import races.f1db.model.tables.Laptimes;
import races.f1db.model.tables.Pitstops;
import races.f1db.model.tables.Qualifying;
import races.f1db.model.tables.Races;
import races.f1db.model.tables.Results;
import races.f1db.model.tables.Seasons;
import races.f1db.model.tables.Status;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index CIRCUITS_PKEY = Indexes0.CIRCUITS_PKEY;
    public static final Index CIRCUITS_URL_KEY = Indexes0.CIRCUITS_URL_KEY;
    public static final Index CONSTRUCTORRESULTS_PKEY = Indexes0.CONSTRUCTORRESULTS_PKEY;
    public static final Index CONSTRUCTORS_NAME_KEY = Indexes0.CONSTRUCTORS_NAME_KEY;
    public static final Index CONSTRUCTORS_PKEY = Indexes0.CONSTRUCTORS_PKEY;
    public static final Index CONSTRUCTORSTANDINGS_PKEY = Indexes0.CONSTRUCTORSTANDINGS_PKEY;
    public static final Index DRIVERS_PKEY = Indexes0.DRIVERS_PKEY;
    public static final Index DRIVERS_URL_KEY = Indexes0.DRIVERS_URL_KEY;
    public static final Index DRIVERSTANDINGS_PKEY = Indexes0.DRIVERSTANDINGS_PKEY;
    public static final Index INDEX_ID = Indexes0.INDEX_ID;
    public static final Index LAPTIMES_PKEY = Indexes0.LAPTIMES_PKEY;
    public static final Index PITSTOPS_PKEY = Indexes0.PITSTOPS_PKEY;
    public static final Index PITSTOPS_RACEID_IDX = Indexes0.PITSTOPS_RACEID_IDX;
    public static final Index QUALIFYING_PKEY = Indexes0.QUALIFYING_PKEY;
    public static final Index RACES_PKEY = Indexes0.RACES_PKEY;
    public static final Index RACES_URL_KEY = Indexes0.RACES_URL_KEY;
    public static final Index RESULTS_PKEY = Indexes0.RESULTS_PKEY;
    public static final Index SEASONS_PKEY = Indexes0.SEASONS_PKEY;
    public static final Index SEASONS_URL_KEY = Indexes0.SEASONS_URL_KEY;
    public static final Index STATUS_PKEY = Indexes0.STATUS_PKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index CIRCUITS_PKEY = Internal.createIndex("circuits_pkey", Circuits.CIRCUITS, new OrderField[] { Circuits.CIRCUITS.CIRCUITID }, true);
        public static Index CIRCUITS_URL_KEY = Internal.createIndex("circuits_url_key", Circuits.CIRCUITS, new OrderField[] { Circuits.CIRCUITS.URL }, true);
        public static Index CONSTRUCTORRESULTS_PKEY = Internal.createIndex("constructorresults_pkey", Constructorresults.CONSTRUCTORRESULTS, new OrderField[] { Constructorresults.CONSTRUCTORRESULTS.CONSTRUCTORRESULTSID }, true);
        public static Index CONSTRUCTORS_NAME_KEY = Internal.createIndex("constructors_name_key", Constructors.CONSTRUCTORS, new OrderField[] { Constructors.CONSTRUCTORS.NAME }, true);
        public static Index CONSTRUCTORS_PKEY = Internal.createIndex("constructors_pkey", Constructors.CONSTRUCTORS, new OrderField[] { Constructors.CONSTRUCTORS.CONSTRUCTORID }, true);
        public static Index CONSTRUCTORSTANDINGS_PKEY = Internal.createIndex("constructorstandings_pkey", Constructorstandings.CONSTRUCTORSTANDINGS, new OrderField[] { Constructorstandings.CONSTRUCTORSTANDINGS.CONSTRUCTORSTANDINGSID }, true);
        public static Index DRIVERS_PKEY = Internal.createIndex("drivers_pkey", Drivers.DRIVERS, new OrderField[] { Drivers.DRIVERS.DRIVERID }, true);
        public static Index DRIVERS_URL_KEY = Internal.createIndex("drivers_url_key", Drivers.DRIVERS, new OrderField[] { Drivers.DRIVERS.URL }, true);
        public static Index DRIVERSTANDINGS_PKEY = Internal.createIndex("driverstandings_pkey", Driverstandings.DRIVERSTANDINGS, new OrderField[] { Driverstandings.DRIVERSTANDINGS.DRIVERSTANDINGSID }, true);
        public static Index INDEX_ID = Internal.createIndex("index_id", Laptimes.LAPTIMES, new OrderField[] { Laptimes.LAPTIMES.RACEID }, false);
        public static Index LAPTIMES_PKEY = Internal.createIndex("laptimes_pkey", Laptimes.LAPTIMES, new OrderField[] { Laptimes.LAPTIMES.RACEID, Laptimes.LAPTIMES.DRIVERID, Laptimes.LAPTIMES.LAP }, true);
        public static Index PITSTOPS_PKEY = Internal.createIndex("pitstops_pkey", Pitstops.PITSTOPS, new OrderField[] { Pitstops.PITSTOPS.RACEID, Pitstops.PITSTOPS.DRIVERID, Pitstops.PITSTOPS.STOP }, true);
        public static Index PITSTOPS_RACEID_IDX = Internal.createIndex("pitstops_raceid_idx", Pitstops.PITSTOPS, new OrderField[] { Pitstops.PITSTOPS.RACEID }, false);
        public static Index QUALIFYING_PKEY = Internal.createIndex("qualifying_pkey", Qualifying.QUALIFYING, new OrderField[] { Qualifying.QUALIFYING.QUALIFYID }, true);
        public static Index RACES_PKEY = Internal.createIndex("races_pkey", Races.RACES, new OrderField[] { Races.RACES.RACEID }, true);
        public static Index RACES_URL_KEY = Internal.createIndex("races_url_key", Races.RACES, new OrderField[] { Races.RACES.URL }, true);
        public static Index RESULTS_PKEY = Internal.createIndex("results_pkey", Results.RESULTS, new OrderField[] { Results.RESULTS.RESULTID }, true);
        public static Index SEASONS_PKEY = Internal.createIndex("seasons_pkey", Seasons.SEASONS, new OrderField[] { Seasons.SEASONS.YEAR }, true);
        public static Index SEASONS_URL_KEY = Internal.createIndex("seasons_url_key", Seasons.SEASONS, new OrderField[] { Seasons.SEASONS.URL }, true);
        public static Index STATUS_PKEY = Internal.createIndex("status_pkey", Status.STATUS, new OrderField[] { Status.STATUS.STATUSID }, true);
    }
}
