/*
 * This file is generated by jOOQ.
 */
package races.f1db.model;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.circuits_circuitid_seq</code>
     */
    public static final Sequence<Integer> CIRCUITS_CIRCUITID_SEQ = new SequenceImpl<Integer>("circuits_circuitid_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.constructorresults_constructorresultsid_seq</code>
     */
    public static final Sequence<Integer> CONSTRUCTORRESULTS_CONSTRUCTORRESULTSID_SEQ = new SequenceImpl<Integer>("constructorresults_constructorresultsid_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.constructors_constructorid_seq</code>
     */
    public static final Sequence<Integer> CONSTRUCTORS_CONSTRUCTORID_SEQ = new SequenceImpl<Integer>("constructors_constructorid_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.constructorstandings_constructorstandingsid_seq</code>
     */
    public static final Sequence<Integer> CONSTRUCTORSTANDINGS_CONSTRUCTORSTANDINGSID_SEQ = new SequenceImpl<Integer>("constructorstandings_constructorstandingsid_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.drivers_driverid_seq</code>
     */
    public static final Sequence<Integer> DRIVERS_DRIVERID_SEQ = new SequenceImpl<Integer>("drivers_driverid_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.driverstandings_driverstandingsid_seq</code>
     */
    public static final Sequence<Integer> DRIVERSTANDINGS_DRIVERSTANDINGSID_SEQ = new SequenceImpl<Integer>("driverstandings_driverstandingsid_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.qualifying_qualifyid_seq</code>
     */
    public static final Sequence<Integer> QUALIFYING_QUALIFYID_SEQ = new SequenceImpl<Integer>("qualifying_qualifyid_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.races_raceid_seq</code>
     */
    public static final Sequence<Integer> RACES_RACEID_SEQ = new SequenceImpl<Integer>("races_raceid_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.results_resultid_seq</code>
     */
    public static final Sequence<Integer> RESULTS_RESULTID_SEQ = new SequenceImpl<Integer>("results_resultid_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.status_statusid_seq</code>
     */
    public static final Sequence<Integer> STATUS_STATUSID_SEQ = new SequenceImpl<Integer>("status_statusid_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));
}
