/*
 * This file is generated by jOOQ.
 */
package races.f1db.model;


import javax.annotation.Generated;

import races.f1db.model.tables.Circuits;
import races.f1db.model.tables.Constructorresults;
import races.f1db.model.tables.Constructors;
import races.f1db.model.tables.Constructorstandings;
import races.f1db.model.tables.Drivers;
import races.f1db.model.tables.Driverstandings;
import races.f1db.model.tables.Laptimes;
import races.f1db.model.tables.Pitstops;
import races.f1db.model.tables.Qualifying;
import races.f1db.model.tables.Races;
import races.f1db.model.tables.Results;
import races.f1db.model.tables.Seasons;
import races.f1db.model.tables.Status;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.circuits</code>.
     */
    public static final Circuits CIRCUITS = races.f1db.model.tables.Circuits.CIRCUITS;

    /**
     * The table <code>public.constructorresults</code>.
     */
    public static final Constructorresults CONSTRUCTORRESULTS = races.f1db.model.tables.Constructorresults.CONSTRUCTORRESULTS;

    /**
     * The table <code>public.constructors</code>.
     */
    public static final Constructors CONSTRUCTORS = races.f1db.model.tables.Constructors.CONSTRUCTORS;

    /**
     * The table <code>public.constructorstandings</code>.
     */
    public static final Constructorstandings CONSTRUCTORSTANDINGS = races.f1db.model.tables.Constructorstandings.CONSTRUCTORSTANDINGS;

    /**
     * The table <code>public.drivers</code>.
     */
    public static final Drivers DRIVERS = races.f1db.model.tables.Drivers.DRIVERS;

    /**
     * The table <code>public.driverstandings</code>.
     */
    public static final Driverstandings DRIVERSTANDINGS = races.f1db.model.tables.Driverstandings.DRIVERSTANDINGS;

    /**
     * The table <code>public.laptimes</code>.
     */
    public static final Laptimes LAPTIMES = races.f1db.model.tables.Laptimes.LAPTIMES;

    /**
     * The table <code>public.pitstops</code>.
     */
    public static final Pitstops PITSTOPS = races.f1db.model.tables.Pitstops.PITSTOPS;

    /**
     * The table <code>public.qualifying</code>.
     */
    public static final Qualifying QUALIFYING = races.f1db.model.tables.Qualifying.QUALIFYING;

    /**
     * The table <code>public.races</code>.
     */
    public static final Races RACES = races.f1db.model.tables.Races.RACES;

    /**
     * The table <code>public.results</code>.
     */
    public static final Results RESULTS = races.f1db.model.tables.Results.RESULTS;

    /**
     * The table <code>public.seasons</code>.
     */
    public static final Seasons SEASONS = races.f1db.model.tables.Seasons.SEASONS;

    /**
     * The table <code>public.status</code>.
     */
    public static final Status STATUS = races.f1db.model.tables.Status.STATUS;
}
