/*
 * This file is generated by jOOQ.
 */
package races.f1db.model.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import races.f1db.model.Indexes;
import races.f1db.model.Keys;
import races.f1db.model.Public;
import races.f1db.model.tables.records.ConstructorsRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Constructors extends TableImpl<ConstructorsRecord> {

    private static final long serialVersionUID = 604930463;

    /**
     * The reference instance of <code>public.constructors</code>
     */
    public static final Constructors CONSTRUCTORS = new Constructors();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ConstructorsRecord> getRecordType() {
        return ConstructorsRecord.class;
    }

    /**
     * The column <code>public.constructors.constructorid</code>.
     */
    public final TableField<ConstructorsRecord, Integer> CONSTRUCTORID = createField("constructorid", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('constructors_constructorid_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.constructors.constructorref</code>.
     */
    public final TableField<ConstructorsRecord, String> CONSTRUCTORREF = createField("constructorref", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false).defaultValue(org.jooq.impl.DSL.field("''::character varying", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.constructors.name</code>.
     */
    public final TableField<ConstructorsRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false).defaultValue(org.jooq.impl.DSL.field("''::character varying", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.constructors.nationality</code>.
     */
    public final TableField<ConstructorsRecord, String> NATIONALITY = createField("nationality", org.jooq.impl.SQLDataType.VARCHAR(255).defaultValue(org.jooq.impl.DSL.field("NULL::character varying", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.constructors.url</code>.
     */
    public final TableField<ConstructorsRecord, String> URL = createField("url", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false).defaultValue(org.jooq.impl.DSL.field("''::character varying", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * Create a <code>public.constructors</code> table reference
     */
    public Constructors() {
        this(DSL.name("constructors"), null);
    }

    /**
     * Create an aliased <code>public.constructors</code> table reference
     */
    public Constructors(String alias) {
        this(DSL.name(alias), CONSTRUCTORS);
    }

    /**
     * Create an aliased <code>public.constructors</code> table reference
     */
    public Constructors(Name alias) {
        this(alias, CONSTRUCTORS);
    }

    private Constructors(Name alias, Table<ConstructorsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Constructors(Name alias, Table<ConstructorsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Constructors(Table<O> child, ForeignKey<O, ConstructorsRecord> key) {
        super(child, key, CONSTRUCTORS);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.CONSTRUCTORS_NAME_KEY, Indexes.CONSTRUCTORS_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<ConstructorsRecord, Integer> getIdentity() {
        return Keys.IDENTITY_CONSTRUCTORS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ConstructorsRecord> getPrimaryKey() {
        return Keys.CONSTRUCTORS_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ConstructorsRecord>> getKeys() {
        return Arrays.<UniqueKey<ConstructorsRecord>>asList(Keys.CONSTRUCTORS_PKEY, Keys.CONSTRUCTORS_NAME_KEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Constructors as(String alias) {
        return new Constructors(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Constructors as(Name alias) {
        return new Constructors(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Constructors rename(String name) {
        return new Constructors(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Constructors rename(Name name) {
        return new Constructors(name, null);
    }
}
